# Permalinks
permalink:           pretty

# Setup
title:               R. Macaraeg
tagline:             Data Science Nub
url:                 https://github.com/rmacaraeg/rmacaraeg.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Randy Macaraeg
  url:               https://twitter.com/randysmac
  email:             randy.macaraeg@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/rrmacaraeg

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
